services:
  app:
    container_name: ${NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_URL: https://github.com/Fydyr/discord-bot.git
        GIT_BRANCH: main
    networks:
      - lan
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      DISCORD_GUILD_ID: "${DISCORD_GUILD_ID}"
      STATUS_CHANNEL_ID: "${STATUS_CHANNEL_ID}"
      ANECDOTE_CHANNEL_ID: "${ANECDOTE_CHANNEL_ID}"
      LOG_WEBHOOK_URL: "${LOG_WEBHOOK_URL}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      NODE_ENV: production

networks:
  lan:
    external: false
    name: lan_${NAME}
